name: moralink
description: "A new dharma provider."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6

  # Firebase
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.4.3
  firebase_storage: ^11.0.14
  firebase_messaging: ^14.9.3

  # Sign in
  google_sign_in: ^6.2.1

  # State Management
  provider: ^6.0.5

  # Navigation
  go_router: ^14.1.3
  url_strategy: ^0.2.0

  # HTTP & JSON
  http: ^1.2.1
  json_annotation: ^4.8.0

  # QR Code
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  # Utils
  path_provider: ^2.0.13
  url_launcher: ^6.1.9
  share_plus: ^9.0.0
  cached_network_image: ^3.2.3
  flutter_datetime_picker: ^1.5.1
  dropdown_button2: ^2.3.9
  geolocator: ^12.0.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.2.3
  sign_in_button: ^3.0.0
  uuid: ^4.4.0

  # Analytics
  firebase_analytics: ^10.1.4

  # Crashlytics
  firebase_crashlytics: ^3.0.15




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

  build_runner: ^2.3.3
  json_serializable: ^6.6.1


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/images/moralink_logo.png
   - assets/images/moralink_logo_with_text.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
